"""add_error_msg_to_file_record

Revision ID: 598a0c6a49e2
Revises: 139e4dd3876c
Create Date: 2026-03-11 10:01:39.460319

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '598a0c6a49e2'
down_revision: Union[str, None] = '139e4dd3876c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('file_records', sa.Column('error_msg', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('file_records', 'error_msg')
    # ### end Alembic commands ###
